
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           38012
     no. of nonzeroes in lower triangle of a =          261277
     no. of nonzeroes in the factor l        =         5712171
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            2677
     maximum order of a front matrix         =            1018
     maximum size of a front matrix          =          518671
     maximum size of a front trapezoid       =          459361
     METIS reordering method used 
     no. of floating point ops for factor    =      1.7831D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           38012
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               1
     number of cores used                    =               1
     time (cpu & wall) for structure input   =        0.000000        0.009458
     time (cpu & wall) for ordering          =        0.265625        0.294702
     time (cpu & wall) for other matrix prep =        0.031250        0.039841
     time (cpu & wall) for value input       =        0.000000        0.007809
     time (cpu & wall) for matrix distrib.   =        0.031250        0.022956
     time (cpu & wall) for numeric factor    =        0.125000        0.146689
     computational rate (gflops) for factor  =       14.264414       12.155320
     time (cpu & wall) for numeric solve     =        0.015625        0.015316
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        589824.        4. MB        584360.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        589824.        4. MB        584360.        4. MB


  Total Solver Memory allocated              =       72.287 MB
